version: '3'
services:
  app:
    image: your-docker-hub-username/your-project:latest
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: "mysql:latest" # Используйте соответствующий образ для вашей базы данных
    environment:
      MYSQL_DATABASE: your_database_name
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    ports:
      - "3306:3306"
